apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecarrier-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecarrierservice
  template:
    metadata:
      labels:
        app: kubecarrierservice
    spec:
      containers:
        - name: kubecarrierservice
          image: kylemorton5770/kubecarrier
---
apiVersion: v1
kind: Service
metadata:
  name: kubecarrier-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: kubecarrierservice
  ports:
  - name: kubecarrierservice
    protocol: TCP
    port: 80
    targetPort: 80