apiVersion: v1
kind: Service
metadata:
  name:  kubecustomernpservice-srv
spec:
  type: NodePort
  selector:
    app: kubecustomernpservice
  ports:
    - name: kubecustomernpservice
      protocol: TCP
      port: 80
      targetPort: 80