apiVersion: v1
kind: Service
metadata:
  name:  kubecarriernpservice-srv
spec:
  type: NodePort
  selector:
    app: kubecarriernpservice
  ports:
    - name: kubecarriernpservice
      protocol: TCP
      port: 80
      targetPort: 80