apiVersion: v1
kind: Service
metadata:
  name:  kubetmsnpservice-srv
spec:
  type: NodePort
  selector:
    app: kubetmsnpservice
  ports:
    - name: kubetmsnpservice
      protocol: TCP
      port: 80
      targetPort: 80